- name: Set authentification mode to AD
  command: "/usr/share/lemonldap-ng/bin/lemonldap-ng-cli -yes 1 set authentication 'AD' | /usr/share/lemonldap-ng/bin/lemonldap-ng-cli -yes 1 set userDB 'AD' | /usr/share/lemonldap-ng/bin/lemonldap-ng-cli -yes 1 set passwordDB 'AD'"

- name: Set Ldap Server IP
  command: "/usr/share/lemonldap-ng/bin/lemonldap-ng-cli -yes 1 set ldapServer '{{ ldap_server_ip }}'"

- name: Set Ldap Server Port
  command : "/usr/share/lemonldap-ng/bin/lemonldap-ng-cli -yes 1 set ldapPort '{{ ldap_port }}'"

- name: Set Ldap Server Verification
  command: "/usr/share/lemonldap-ng/bin/lemonldap-ng-cli -yes 1 set ldapVerify '{{ ldap_verification }}'"

- name: Set Ldap Timeout
  command: "/usr/share/lemonldap-ng/bin/lemonldap-ng-cli -yes 1 set ldapTimeout '{{ ldap_timeout }}'"

- name: Set Ldap Base
  command: "/usr/share/lemonldap-ng/bin/lemonldap-ng-cli -yes 1 set ldapBase '{{ ldap_base }}'"

- name: Set Ldap Account
  command: "/usr/share/lemonldap-ng/bin/lemonldap-ng-cli -yes 1 set managerDn '{{ ldap_account }}'"

- name: Set Ldap Password
  command: "/usr/share/lemonldap-ng/bin/lemonldap-ng-cli -yes 1 set managerPassword '{{ ldap_password }}'"

- name: Generate  private key and self-signed certificate for SAML Identity Provider
  command: "openssl req -new -newkey rsa:4096 -keyout saml.key -nodes -out saml.pem -x509 -days 3650 -subj '/C=/ST=/L=/O=/OU=/CN={{ lemonldap_domain }}'"
  when: activate_SAML == 'yes'

- name: Fixing certificate key format (1/2)
  command: "sed -e 's/END PRIVATE/END RSA PRIVATE/' -i saml.key"
  when: activate_SAML == 'yes'

- name: Fixing certificate key format (2/2)
  command: "sed -e 's/BEGIN PRIVATE/BEGIN RSA PRIVATE/' -i saml.key"
  when: activate_SAML == 'yes'

- name: Importing private key (1/2)
  command: "cat saml.key"
  register: cat_saml_key
  when: activate_SAML == 'yes'

- name: Importing private key (2/2)
  command: "/usr/share/lemonldap-ng/bin/lemonldap-ng-cli -yes 1 set samlServicePrivateKeySig '{{ cat_saml_key.stdout }}'"
  when: activate_SAML == 'yes'
  
- name: Importing certificate (1/2)
  command: "cat saml.pem"
  register: cat_saml_pem
  when: activate_SAML == 'yes' 
  
- name: Importing certificate (2/2)
  command: "/usr/share/lemonldap-ng/bin/lemonldap-ng-cli -yes 1 set samlServicePublicKeySig '{{ cat_saml_pem.stdout  }}'"
  when: activate_SAML == 'yes'
  
- name: Activate SAML
  command: "/usr/share/lemonldap-ng/bin/lemonldap-ng-cli -yes 1 set issuerDBSAMLActivation 1"
  when: activate_SAML == 'yes'

- name: Copy Custom Main Logo
  copy: src=skin_customization/{{ custom_main_logo }} dest=/usr/share/lemonldap-ng/portal/htdocs/static/common/logos
  when: custom_main_logo != 'default'
  
- name: Set Custom Main Logo
  command: "/usr/share/lemonldap-ng/bin/lemonldap-ng-cli -yes 1 set portalMainLogo /common/logos/'{{ custom_main_logo }}'"
  when: custom_main_logo != 'default'
  
- name: Copy Custom Favicon
  copy: src=skin_customization/{{ custom_favicon }} dest=/usr/share/lemonldap-ng/portal/htdocs/static/common/logos
  when: custom_favicon != 'default'
  
- name: Set Custom Favicon
  command: "/usr/share/lemonldap-ng/bin/lemonldap-ng-cli -yes 1 set portalFavicon /common/logos/'{{ custom_favicon }}'"
  when: custom_favicon != 'default'
  
- name: Copy Custom Background
  copy: src=skin_customization/{{ custom_background }} dest=/usr/share/lemonldap-ng/portal/htdocs/static/common/backgrounds
  when: custom_background != 'default'
  
- name: Set Custom Background
  command: "/usr/share/lemonldap-ng/bin/lemonldap-ng-cli -yes 1 set portalSkinBackground '{{ custom_background }}'"
  when: custom_background != 'default'

- name: Restart Apache Service
  command: "systemctl restart apache2.service"
  when: lemonldap_webserver == 'apache'

- name: Restart Nginx Service (1/2)
  command: "systemctl restart lemonldap-ng-fastcgi-server.service"
  when: lemonldap_webserver == 'nginx'

- name: Restart Nginx Service (2/2)
  command: "systemctl restart nginx"
  when: lemonldap_webserver == 'nginx'

- name: Delete all playbook files
  shell: "rm -rf *"
  when: delete_files == 'yes'

